[env:esp32-c3-zero]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_mode = dio
board_build.embed_txtfiles =
  web/wifi_portal.html
lib_deps =
  adafruit/Adafruit NeoPixel
